name: CVFX
main: org.cubeville.effects.Effects
author: KipperOrigin, GoalieGuy6, FrediW
version: 1.20
api-version: 1.18

depend: [CVTools]

commands:
  fx:
    description: effects management command
    usage: /fx
    permission: fx.admin
