name: CVFX
main: org.cubeville.effects.Effects
author: KipperOrigin, GoalieGuy6, FrediW
version: 1.21
api-version: 1.21

depend: [CVTools]
softdepend: [CVEntityEdit,Citizens]

commands:
  fx:
    description: effects management command
    usage: /fx
    permission: fx.admin
